export default {
  activityRules:
    '{\n"lotteryRule":[\n  {"context":"暑期在读学生续报秋季课程即有抽奖机会"},\n  {"context":"中奖概率：100%中奖"}\n],\n "lotterySend":[\n        {\n            "title":"特等奖",\n            "context":"购课费用会在暑期上课最后一节当天24时前按付款方式原路退回",\n            "url":"//banzhuren-assistant.oss-cn-beijing.aliyuncs.com/gorgons/images/raffle/best_icon.png"\n        },\n        {\n            "title":"金币奖品",\n            "context":"金币将在暑期上课最后一节当天24时前发放至购课账号",\n            "url":"//banzhuren-assistant.oss-cn-beijing.aliyuncs.com/gorgons/images/raffle/coin_icon.png"\n        },\n        {\n            "title":"实物奖品",\n            "context":"奖品将和秋季教材一起寄出（礼盒两种样式随机发放、书包黄色蓝色随机发放）",\n           "url": "//banzhuren-assistant.oss-cn-beijing.aliyuncs.com/gorgons/images/raffle/gift_icon.png"\n        }\n    ]\n}',
  begin: false,
  endDelayTime: "2020-07-28 18:05:00",
  endTime: "2020-07-28 18:00:00",
  id: 10,
  isBegin: false,
  lotteryWinList: null,
  name: "2020暑期抽奖一期",
  nextEndDelayTime: "2020-08-10 18:05:00",
  nextEndTime: "2020-08-10 18:00:00",
  nextStartTime: "2020-07-20 00:00:00",
  pgRewardRulesList: [
    {
      id: 22,
      name: "特等奖",
      rewardContent: "免单",
      rewardDescribe: "",
      rewardDrawId: 10,
      rewardProbabilty: null,
      rewardValue: "免本次报名金额",
      rewardValueType: "word",
    },
    {
      id: 23,
      name: "四等奖",
      rewardContent: "500金币",
      rewardDescribe: "",
      rewardDrawId: 10,
      rewardProbabilty: null,
      rewardValue: "//banzhuren-assistant.oss-cn-beijing.aliyuncs.com/gorgons/images/raffle/jinbi3.png",
      rewardValueType: "picture",
    },
    {
      id: 24,
      name: "一等奖",
      rewardContent: "狸米礼盒",
      rewardDescribe: "礼品和秋季教材一起寄出",
      rewardDrawId: 10,
      rewardProbabilty: null,
      rewardValue: "//banzhuren-assistant.oss-cn-beijing.aliyuncs.com/gorgons/images/raffle/lihe.png",
      rewardValueType: "picture",
    },
    {
      id: 25,
      name: "六等奖",
      rewardContent: "100金币",
      rewardDescribe: "",
      rewardDrawId: 10,
      rewardProbabilty: null,
      rewardValue: "//banzhuren-assistant.oss-cn-beijing.aliyuncs.com/gorgons/images/raffle/jinbi1.png",
      rewardValueType: "picture",
    },
    {
      id: 26,
      name: "三等奖",
      rewardContent: "狸米公仔",
      rewardDescribe: "礼品和秋季教材一起寄出",
      rewardDrawId: 10,
      rewardProbabilty: null,
      rewardValue: "//banzhuren-assistant.oss-cn-beijing.aliyuncs.com/gorgons/images/raffle/gongzai.png",
      rewardValueType: "picture",
    },
    {
      id: 27,
      name: "五等奖",
      rewardContent: "300金币",
      rewardDescribe: "",
      rewardDrawId: 10,
      rewardProbabilty: null,
      rewardValue: "//banzhuren-assistant.oss-cn-beijing.aliyuncs.com/gorgons/images/raffle/jinbi2.png",
      rewardValueType: "picture",
    },
    {
      id: 28,
      name: "二等奖",
      rewardContent: "书包",
      rewardDescribe: "礼品和秋季教材一起寄出",
      rewardDrawId: 10,
      rewardProbabilty: null,
      rewardValue: "//banzhuren-assistant.oss-cn-beijing.aliyuncs.com/gorgons/images/raffle/bag.png",
      rewardValueType: "picture",
    },
  ],
  startTime: "2020-07-20 00:00:00",
  summerOnePeriod: false,
  summerOnePeriodDelay: false,
  summerThreePeriod: false,
  summerThreePeriodDelay: false,
  summerTwoPeriod: false,
  summerTwoPeriodDelay: false,
  threeDelayTime: "2020-08-22 18:05:00",
  threeEndSendTime: "2020-08-25 23:59:59",
  threeEndTime: "2020-08-22 18:00:00",
  threeSendTime: "2020-08-25 21:00:00",
  threeStartTime: "2020-07-20 00:00:00",
};
